<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="generator" content="Pomf {{pkgVersion}}">
		<title>{{siteName}} &middot; {% block title %}Kawaii File Hosting{% endblock %}</title>
		<link rel="icon" href="favicon.ico">
		<link rel="stylesheet" href="pomf.min.css">
		<script src="pomf.min.js"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118598884-1"></script>
		<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

  gtag('config', 'UA-118598884-1');
</script>

	</head>
	<body>
		<div class="container">
			{% block body %}What the fuck are you doing here, <span lang="jp">baka</span>?{% endblock %}
		</div>
	</body>
</html>
